name: w_common
version: 3.4.0
description: General utilities for Dart projects.
homepage: https://www.github.com/Workiva/w_common
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  intl: '>=0.17.0 <0.19.0'
  js: ^0.6.3
  logging: ^1.0.0
  meta: ^1.16.0
dev_dependencies:
  build_runner: ^2.0.0
  build_test: ^2.0.0
  build_web_compilers: '>=3.0.0 <5.0.0'
  dependency_validator: ^3.0.0
  mocktail: ^1.0.4
  test: ^1.21.1
  workiva_analysis_options: ^1.4.2
